name: Upload release to GitHub

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions: write-all

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Build package
        run: hatch build

      - name: Set the Version
        run: |
          grep_result=$(grep -E '__version__ = ".*"' pyrogram/__init__.py)
          prefix="__version__ = \""
          suffix="\""
          final_value=${grep_result#"$prefix"}
          final_value=${final_value%"$suffix"}
          echo "CURRENT_LIB_VERSION=$(echo 'v'$final_value)" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.CURRENT_LIB_VERSION }}
          title: ${{ env.CURRENT_LIB_VERSION }}
          prerelease: false

      - name: Upload Release Asset (sdist)
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_LIB_VERSION }}
          files: dist/*
